name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Woops! Have we done something wrong? If so, publish the issueand we will fix it ;)"
        pr-message: "Hello! Hoping your having a nice day, thank you for the pull request!"
